### ISSUE TITLE
Update soundfield transform figures to illustrate rE

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#11]
Update the indication of perceived localization focus from |rV| to |rE|.

Mapping to |rE| offers a stronger sense of how localized an encoded planewave will appear after transform.

This change is parallel to [issue no. 24 for atk-reaper](https://github.com/ambisonictoolkit/atk-reaper/issues/24).

**Comment by joslloand** [comment]
Will need to edit python code. As this hasn't been run in some time, there's a risk of failure here....

**Comment by joslloand** [comment]
Closed with:
2b2e10e299c1c10fcb26f2d7db5e4f20a2ae3de8
4f6d2fc5d52a07f85e7a34728700a9492ef8d346

And merged into sc3-plugins

**Comment by lossius** [comment]
Thanks, I 'll use those commits in order to do the same change in atk-reaper.

**Comment by joslloand** [comment]
Hi @lossius 

Discussion is [here](https://github.com/ambisonictoolkit/atk-reaper/issues/24#issuecomment-233417052), with comments on calculating:
- [gain](https://github.com/ambisonictoolkit/atk-reaper/issues/24#issuecomment-233421937)
- [active_energy_vector](https://github.com/ambisonictoolkit/atk-reaper/issues/24#issuecomment-233428182)
- [active_admittance_vector](https://github.com/ambisonictoolkit/atk-reaper/issues/24#issuecomment-233432763)
