### ISSUE TITLE
refactor .mosl comment character from \\ to # or ;

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#113]
@lossius:

> So, if I understand you correctly, the following two would be correct comment lines:
>
> `# This is a comment`
> `; This is a comment`
>
> while the following is not a correct comment line:
>
> // This is not the way to do a comment

Justin Frankel:
> That’s correct

**Comment by joslloand** [comment]
Relevant code:

- [ATKMatrix:-prWriteMatrixToMOSL](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/ATKMatrix.sc#L178-L198)
- [FoaMatrix:-prParseMOSL](https://github.com/ambisonictoolkit/atk-sc3/blob/master/Classes/FoaMatrix.sc#L409-L459)

**Comment by joslloand** [comment]
@mtmccrea, are you up for reviewing this?

**Comment by lossius** [comment]
It would be good to fix this sooner rather than later, as the encoders/decords between B and AmbiX are currently broken in ATK for Reaper. Considering that ATK still uses FuMa while everything else uses AmbiX that is unfortunate.

**Comment by joslloand** [comment]
... will prioritize...

**Comment by joslloand** [comment]
fixed: efc19212eab372dc044875cc2fb0343e58fb490b
