### ISSUE TITLE
Automatic download of matrices doesn't work

### ISSUE THREAD

**Issue by dyfer** [ambisonictoolkit/atk-sc3#115]
`Atk.downloadMatrices` does not currently work.

The reason is that the [matrices latest release ](https://github.com/ambisonictoolkit/atk-matrices/releases/latest) does not include the `matrices.zip` file.
Getting a download link to the "source code" archive for the release seems to be [somewhat complicated](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-3705619). 

I see two solutions:
- implement the complicated mechanism for downloading "latest source code" for the matrices in `atk-sc3`
- created `matrices.zip` for the latest and subsequent releases
  - in that case I'd be happy to contribute github actions automation to facilitate that
  - we can also manually create that zip...
- if new release of the kernels will be made at some point, the same issue will apply

What do you think @joslloand ?

**Comment by joslloand** [comment]
@dyfer, argh!

I'll bet we (I?) manually made the `matrices.zip` file for the previous release, but forgot to do so this time!

Agreed, the same issue will come up for any future updates.

How easy / straightforward would it be to make a _github action_ that does the job? If easily doable, doing so sounds like a nice automagic solution.

If we do go this way, having a similar solution for [atk-kernels](https://github.com/ambisonictoolkit/atk-kernels) would be good, too!

**Comment by dyfer** [comment]
It's not hard, I'm happy to do it.

Does the zip include all the contents of the repo (sans hidden files etc)?

**Comment by joslloand** [comment]
@dyfer, yep! All contents except hidden files.

THANKS!!!

**Comment by joslloand** [comment]
fixed with: https://github.com/ambisonictoolkit/atk-matrices/commit/7f8ae896ee5b06df9bb5307d80e964a39a48956f
