### ISSUE TITLE
Incorrect links for Kernel installation

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#16]
Incorrect links for Kernel installation are listed in Help for [FoaEncoderKernel](http://doc.sccode.org/Classes/FoaEncoderKernel.html) & [FoaDecoderKernel](http://doc.sccode.org/Classes/FoaDecoderKernel.html).

**Comment by dmartinp** [comment]
Fixed

**Comment by joslloand** [comment]
@dmartinp, have you merged this into the master branch? I don't see any commits.

Once you've done that, you can hit the "Close and comment" button to close this bug.

**Comment by joslloand** [comment]
merged into sc3-plugins by @joslloand
