### ISSUE TITLE
Improve NRT handling of Kernels

### ISSUE THREAD

**Issue by dmartinp** [ambisonictoolkit/atk-sc3#21]
Modify `FoaEncoderKernel` and `FoaDecoderKernel` so that the kernels do not automatically load on the realtime server when using NRT.  The `FoaEncoderKernel` and `FoaDecoderKernel` will take a `Score` or a `CtkScore` as an argument.  When the score is not `nil`, the kernels will be added to the score and not loaded to the realtime server.

**Comment by dmartinp** [comment]
Make sure that old code that handles kernels in NRT with scores will not break.

**Comment by joslloand** [comment]
Merged with master.

@dmartinp, have a look at following up with #22.

Also... I'll be removing branch [NRT-handling-of-kernels](https://github.com/ambisonictoolkit/atk-sc3/tree/NRT-handling-of-kernels), soon.
