### ISSUE TITLE
Update NRT Help Documentation

### ISSUE THREAD

**Issue by dmartinp** [ambisonictoolkit/atk-sc3#22]
Cleanup SynthDef and NRT help file.  Possibly consolidate this with #7.

This will have to accommodate #21 when that change occurs.

**Comment by joslloand** [comment]
@dmartinp, I'm looking at the code in [NRT-handling-of-kernels](https://github.com/ambisonictoolkit/atk-sc3/tree/NRT-handling-of-kernels), and I don't see any updates to `.schelp` files. The additions you've made for #21 add two new vars:

- `sampleRate`
- `score`

We'll need to see a discussion of these (and their use) appear in the related `.schelp` files. I'll go ahead and make the commit for #21 now, but we'll need to have the documentation aspect resolved before this issue (#22) is closed.

**Comment by joslloand** [comment]
@dmartinp, FYI, here's the warnings that I'm seeing when opening the Help for  **FoaDecoderKernel**:

```
WARNING: SCDoc: In /Users/joanders/Library/Application Support/SuperCollider/Extensions/SC3plugins/ATK/HelpSource/Classes/FoaDecoderKernel.schelp
  Method *newUHJ has 4 args, but doc has 2 argument:: tags.
WARNING: SCDoc: In /Users/joanders/Library/Application Support/SuperCollider/Extensions/SC3plugins/ATK/HelpSource/Classes/FoaDecoderKernel.schelp
  Method *newSpherical has 4 args, but doc has 2 argument:: tags.
WARNING: SCDoc: In /Users/joanders/Library/Application Support/SuperCollider/Extensions/SC3plugins/ATK/HelpSource/Classes/FoaDecoderKernel.schelp
  Method *newListen has 4 args, but doc has 2 argument:: tags.
WARNING: SCDoc: In /Users/joanders/Library/Application Support/SuperCollider/Extensions/SC3plugins/ATK/HelpSource/Classes/FoaDecoderKernel.schelp
  Method *newCIPIC has 4 args, but doc has 2 argument:: tags.
```

**Comment by joslloand** [comment]
Corrected.... with commit [3eb2152ebb6a18b58f80626be2143f8eb3b30570](https://github.com/ambisonictoolkit/atk-sc3/commit/3eb2152ebb6a18b58f80626be2143f8eb3b30570)

**Comment by dmartinp** [comment]
Yes, these new args were added to the .schlep files in the workshop-helpfiles branch.  The commit is [aa5eef3606d2f321e8de3a1ce48f1f8ad3cb35be](https://github.com/ambisonictoolkit/atk-sc3/commit/aa5eef3606d2f321e8de3a1ce48f1f8ad3cb35be)

**Comment by dmartinp** [comment]
Also, the I have completely changed the synthdef and NRT help file.  See commit [b7558aea7792ee3ca4ffd598ca5eaa330fcd54da](https://github.com/ambisonictoolkit/atk-sc3/commit/b7558aea7792ee3ca4ffd598ca5eaa330fcd54da)

**Comment by joslloand** [comment]
Reopen for review / integration... cherry picking possibly required.

**Comment by joslloand** [comment]
We probably need to add a harmonic by harmonic test to see what is happening with the use of Score vs CtkScore to diagnose.

**Comment by joslloand** [comment]
Closing this, but note, we do seem to have a bug with the use of Score. Now listed as #31 

We'll want to close the Score bug before the 3.8 release.
