### ISSUE TITLE
Batch Decoding and Batch Encoding and Processing?

### ISSUE THREAD

**Issue by dmartinp** [ambisonictoolkit/atk-sc3#23]
It could be useful to have a set of tools that would run encoders/decoders/transforms on a folder (or even folders?) of sound files.
- Encoders
- Decoders
- Transforms

**Comment by dmartinp** [comment]
For now I have been using the `CtkScore` method, so I should rewrite using `Score` as well.  Also, the kernel encoders are a little tricky.

**Comment by joslloand** [comment]
Also need to include documentation....

**Comment by joslloand** [comment]
This really seems to be an SC project management issue, rather than an ATK library issue.

**Comment by joslloand** [comment]
[HoaVST](https://gitlab.com/dxarts/projects/hoavst.quark) is example made by @dmartinp
