### ISSUE TITLE
FoaEncoderKernel: SuperStereo, broken link in documentation

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#24]
The link at: http://doc.sccode.org/Classes/FoaEncoderKernel.html#footnote_1

Currently points to: http://en.wikipedia.org/wiki/Ambisonics#Super_stereo
Should point to: https://en.wikipedia.org/wiki/Ambisonic_UHJ_format#Super_stereo

**Comment by dmartinp** [comment]
Fixed and committed to workshop-helpfiles branch

**Comment by joslloand** [comment]
merged to sc3-plugins
