### ISSUE TITLE
Transform Display

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#27]
Integrate Soundfield transform display feature developed by @mtmccrea .

Include documentation.

**NOTE:** may want to rename or otherwise add more verbosity to this issue!

**Comment by joslloand** [comment]
May also want to include further soundfield indicators, at a later date.

**Comment by mtmccrea** [comment]
The transform display is actually comprised of at least 3 modules that are linked: (1) the transform display, (2) transform chaining (like an "fx chain"), the result of which is displayed in the transform window, and (3) an auditioner which can be connected to the transform module (and vice versa) and which has some useful sound field players/generators to quickly audition e.g. a particular transform or decoder with a known signal.

We should take a look at each and define the "first release" features to tie up.

**Comment by joslloand** [comment]
Transform display merged to 4.0.0: a3143156a4d865b575098dacc972be19eb405e2b
