### ISSUE TITLE
score vs ctk-score?

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#31]
@dmartinp is there an issue with using score vs ctk-score where not all output files are written correctly?

**Comment by joslloand** [comment]
We probably need to add a harmonic by harmonic test to see what is happening with the use of Score vs CtkScore to diagnose.

**Comment by dmartinp** [comment]
Posted code that I have been working on...  https://gist.github.com/dmartinp/2d56a022f4c2c296fbc01dbb3eacc519

**Comment by dmartinp** [comment]
Fixed with commit [afb7e3634f203abcf9fc796a5037212f74454b76](https://github.com/ambisonictoolkit/atk-sc3/commit/afb7e3634f203abcf9fc796a5037212f74454b76)
