### ISSUE TITLE
Matrix loading/writing

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#4]
Migrate fixed encoding / decoding matrices to use [akt-matrices](https://github.com/ambisonictoolkit/atk-matrices).

This will facilitate the use of matrices generated by external tools, i.e., [ADT](https://bitbucket.org/ambidecodertoolbox/adt.git).

**Comment by joslloand** [comment]
Also dependent on ambisonictoolkit/atk-matrices#4

**Comment by mtmccrea** [comment]
Still to do: add .mosl (matrix-only-single-line) file format reading and writing in SC.

**Comment by mtmccrea** [comment]
Update: .mosl reading and writing added to atk-sc3. Next move: documentation.

**Comment by joslloand** [comment]
Ok... and... I'll look into integrating this for the 3.8 release!

**Comment by joslloand** [comment]
Closed with: 850b27d4ecbf106359d08020503c88dabe64a73a
