### ISSUE TITLE
Migrate issues from former ATK page

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#5]
Review and migrate issues from former ATK page to this issue tracker.

Use archive [found here](https://web.archive.org/web/20150214003850/http://www.ambisonictoolkit.net/wiki/tiki-index.php), and/or other sources.

**Comment by lossius** [comment]
Didn't know that more than one person can be assigned to a ticket, that's cool.

I have migrated all issues for atk-reaper, so I'll now unassign myself.
