### ISSUE TITLE
Migrate fixed matrices to use atk-matrices

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#51]
With the closing of #4, the mechanism for "built-in" matrix loading allows loading [atk-matrices](https://github.com/ambisonictoolkit/atk-matrices). Among other things, this will allow closer integration with various ATK platform deployments.
## 

[**FoaEncoderMatrix**](http://doc.sccode.org/Classes/FoaEncoderMatrix.html)
- [x] `newOmni`
- [x] `newQuad`
- [x] `new5_0`
- [x] `new7_0`
- [x] `newAtoB`
- [x] `newHoa1`
- [x] `newAmbix1` (`newHoa1` alias)
- [x] `newZoomH2n` (`newHoa1` alias)
## 

[**FoaXformerMatrix**](http://doc.sccode.org/Classes/FoaXformerMatrix.html)
- [x] `newMirrorO`
- [x] `newMirrorX`
- [x] `newMirrorY`
- [x] `newMirrorZ`
## 

[**FoaDecoderMatrix**](http://doc.sccode.org/Classes/FoaDecoderMatrix.html)
- [x] `new5_0`
- [x] `newBtoA`
- [x] `newHoa1`
- [x] `newAmbix1` (`newHoa1` alias)

Related to: [atk-reaper issue](https://github.com/ambisonictoolkit/atk-reaper/issues/19)

**Comment by joslloand** [comment]
Also see: [https://github.com/ambisonictoolkit/atk-matrices/issues/4](url)

**Comment by mtmccrea** [comment]
All but new7_0 (encoder) passed the test comparing the new matrices to the old implementation.

Once this is resolved, the test methods preserving the previous functionality can be removed and we can close the issue.

**Comment by joslloand** [comment]
Within tolerance...

> ----------
> 0
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 1
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 2
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 3
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 4
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 5
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 6
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 7
> 1
> 1
> -inf
> ----------
> 8
> 0.86602540378444
> 0.86602540378444
> -309.54937030943
> ----------
> 9
> 6.1232339957368e-17
> 0
> -324.26038287885
> ----------
> 10
> -0.70710678118655
> -0.70710678118655
> -307.05059557726
> ----------
> 11
> -0.70710678118655
> -0.70710678118655
> -307.05059557726
> ----------
> 12
> 6.1232339957368e-17
> 0
> -324.26038287885
> ----------
> 13
> 0.86602540378444
> 0.86602540378444
> -309.54937030943
> ----------
> 14
> 0
> 0
> -inf
> ----------
> 15
> 0.5
> 0.5
> -325.1123953171
> ----------
> 16
> 1
> 1
> -inf
> ----------
> 17
> 0.70710678118655
> 0.70710678118655
> -307.05059557726
> ----------
> 18
> -0.70710678118655
> -0.70710678118655
> -307.05059557726
> ----------
> 19
> -1
> -1
> -inf
> ----------
> 20
> -0.5
> -0.5
> -325.1123953171
> -> 21
> 
>

**Comment by joslloand** [comment]
Also note, will need to update installation instructions as atk-matrices will need to be installed.

**Comment by joslloand** [comment]
All set...
