### ISSUE TITLE
Undocumented class methods: Atk.schelp

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#53]
Atk.schelp

---
**Undocumented class methods:** used in Guide-to-ATK-Matrix-Files.schelp

- [x] createExtensionsDir
- [x] getMatrixExtensionPath (set, type)
- [x] postMyMatrixDir (set, type)
- [x] userExtensionsDir

---
**Undocumented class methods:** check for redundancies with current methods

Document where need be!

- [x] sets
- [x] systemExtensionsDir
- [x] getExtensionPath
- [x] getKernelExtensionPath
- [x] getAtkLibSubPath
- [x] getBuiltInPath
- [x] getMatrixBuiltInPath
- [x] systemMatrixDir
- [x] userMatrixDir
- [x] checkSet
- [x] resolveMtxPath
- [x] folderExists

**Comment by joslloand** [comment]
@mtmccrea, in principle, for this release, documenting the _user accessed_ methods should be the priority. For instance, `getAtkLibSubPath` and `resolveMtxPath` are likely too low level to document—and would add to user confusion!

**Comment by mtmccrea** [comment]
https://github.com/ambisonictoolkit/atk-sc3/commit/f25abed26cb06ab42333777a849fcc4b1a775059 should clean this up. 

It called for a bit of an overhaul of the methods listed, I think for the better. It wouldn't hurt to look it over for continuity, in particular the Atk help file. I've been using the Guide to ATK Matrix Files as the test case for all things matrix read/write/introspect, so it wouldn't hurt if someone else did a quick run though it as well.

**Comment by joslloand** [comment]
Hi @mtmccrea, I've done a merge (but not committed back to remote). There weren't any conflicts, so that's good news. I'll have a careful look through Atk.schelp. Have spotted a few things that could be slightly tighter. And, will have a walk through the Guide-to-ATK-Matrix-Files.

**Comment by joslloand** [comment]
Closed with 204e28a1e66d98697ed2824495b2dbd794c32163
