### ISSUE TITLE
Quaternion support

### ISSUE THREAD

**Issue by jmpetroske** [ambisonictoolkit/atk-sc3#77]
There are many functions involving rotations that use different methods of rotations in space. (i.e. FoaXformerMatrix uses rotate, tilt, tumble). Because the order of these matter, it can be quite easy to get confused. In addition, it can be difficult to get slowly interpolate between two different rotations. Quaternions (an alternate way to represent rotations 3d space) are a great way to solve these issues. Getting quaternion support in ATK could be really cool. I think the first part would be to get quaternion support in supercollider, and then add it to ATK, which I definitely wouldn't mind creating - they could be used outside of ATK as well. Would anybody be else interested in this?

**Comment by joslloand** [comment]
@mtmccrea has implemented rotations for the upcoming HOA version of the ATK. I'll **close** this now.

Maybe @mtmccrea would like to offer a reply?
