### ISSUE TITLE
[FR] Provide an option for amplitude scaling and filtering indicating distance

### ISSUE THREAD

**Issue by dathinaios** [ambisonictoolkit/atk-sc3#78]
During my research on implementing virtual sound environments I have found that Richard Furse's approach for modelling a sound environment in his (unfortunately nowhere to be found) `VSpace` software produced the most immersive result.  His method used, among other techniques, the inverse square law for amplitude scaling and a formula for low pass filtering (a low pass filter cutoff in Hz by providing the distance in metres using the formula `cutoff = 100000 / distance`).

First of all I think having an interface that allows to deal with the space in meters is a great idea and helps build an intuition of the composition space. But more to the point, is there anything in `ATK` that would model the effect of air absorption regarding amplitude and high frequency attenuation? If not I would recommend its addition as it is one of the most important components in creating a convincing spatial image.

**Comment by joslloand** [comment]
As described in https://github.com/ambisonictoolkit/atk-sc3/issues/79, the ATK-SC3 is intended as a toolkit with the relevant parts to build higher level algorithms.

@dmartinp has done some work building an algorithm along the lines you've described, implementing a version of John Chowning's [_mover instrument_](http://www.aes.org/e-lib/browse.cfm?elib=2220) with the ATK-SC3.

You may wish to contact @dmartinp regarding whether there is a plan to make this work public at some point....
