### ISSUE TITLE
[FR] Reverb implementation

### ISSUE THREAD

**Issue by dathinaios** [ambisonictoolkit/atk-sc3#79]
I have asked about this a few years back on the `sc-users` list but don't seem to be a way to search the archive at this point. Are there any plans for an integrated reverb implementation?

Thanks for al the great work by the way!! 😄 👍

**Comment by joslloand** [comment]
Hi @dathinaios 

I'm going to point you to [AmbiVerbSC](https://github.com/JamesWenlock/AmbiVerbSC) by @JamesWenlock.

ATK-SC3 is intended as a toolkit with the relevant parts to build higher level algorithms. [AmbiVerbSC](https://github.com/JamesWenlock/AmbiVerbSC) is an example "tank" style reverb built with the ATK.

You may like to contact @JamesWenlock regarding his work...

**Comment by dathinaios** [comment]
That looks great! Thanks for the info 😄
