### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-sc3#8]
Versioning system needs to be implemented / documented.

**Comment by joslloand** [comment]
There is a question as to how parallel to [atk-reaper](https://github.com/ambisonictoolkit/atk-reaper) this needs to be.

**Comment by lossius** [comment]
I don

**Comment by lossius** [comment]
I don't think that it need to ne parallell at all. We should make sure that both sc3 and reaper use [semantic versioning](http://semver.org/), but there's no need for having 1.2 meaning the same thing between the two implementations.

**Comment by joslloand** [comment]
After some thought and discussion, with atk-sc3 part of the [sc3-plugins](https://github.com/supercollider/sc3-plugins) project, atk-sc3's version numbers are tied to the version numbers dictated by the [supercollider release](https://github.com/supercollider/supercollider/releases) development cycle. This, unfortunately, is **not ideal**, in that atk-sc3 releases will not adhere to the [semantic versioning](http://semver.org/) principles described by Tom Preston-Werner.

For the short term, it looks like the only thing we can do that makes sense is to label atk-sc3 releases with the [sc3-plugins](https://github.com/supercollider/sc3-plugins) versioning. Doing so will mean we can keep track of developments here in terms of the [sc3-plugins](https://github.com/supercollider/sc3-plugins) context.

For the future, we're anticipating **atk-sc3 as a Quark** #3. At this point, atk-sc3 would then be able to have its own [semantic versioning](http://semver.org/) _and_ development cycle.

**Comment by joslloand** [comment]
Note about current versioning for atk-sc3 added to README in 4dcd4e54e5c219ae48c16bdbe488ac280cb8b765
