### ISSUE TITLE
ERROR: matrix singular in Matrix-inverse for some FoaEncoderMatrix configurations

### ISSUE THREAD

**Issue by dyfer** [ambisonictoolkit/atk-sc3#81]
I encountered an error when trying to create a 6-microphone encoder matrix:
```supercollider
FoaEncoderMatrix.newDirections(
	[[0, 0], [60, 0], [120, 0], [180, 0], [240, 0], [300, 0]].degrad,
	((3-sqrt(3))/2) 
)
```
returns
```supercollider
ERROR: matrix singular in Matrix-inverse
```
This seems to depend on directions and polar pattern as neither
```supercollider
FoaEncoderMatrix.newDirections(
	[[0, 0.1], [60, 0], [120, 0], [180, 0], [240, 0], [300, 0]].degrad, //offset elevation of one mic
	((3-sqrt(3))/2) 
)
```
nor
```supercollider
FoaEncoderMatrix.newDirections(
	[[0, 0], [60, 0], [120, 0], [180, 0], [240, 0], [300, 0]].degrad,
	nil //no polar pattern - virtual speakers
)
```
result in this error. 
I haven't investigated the underlying math...

**Comment by joslloand** [comment]
@dyfer, ah...

Try this:

```
// 2D:
~directions = [0, 60, 120, 180, 240, 300].degrad;
~pattern = (3-sqrt(3))/2;  // super-cardioid

~encoder = FoaEncoderMatrix.newDirections(
	~directions, 
	~pattern
)
```

The problem is that ATK FOA reads your rank 2 array:

`[[0, 0], [60, 0], [120, 0], [180, 0], [240, 0], [300, 0]].degrad`

as a 3D array. And, then calls `-initInv3D`. This will then result in:

> ERROR: matrix singular in Matrix-inverse

From the help for `FoaEncoderMatrix *newDirections`:

> **directions**
> An array of directions of the virtual loudspeakers or microphones. Specify in radians.
> Rank 1 arrays return pantophonic, while rank 2 arrays return periphonic. E.g.,
> ```
> // 2D:
> ~directions = [ theta0, theta1, ... thetaN ];
> // 3D:
> ~directions = [ [ theta0, phi0 ], [ theta1, phi1 ], ... [ thetaN, phiN ] ];
> ```

**Comment by dyfer** [comment]
Thank you for clarifying!
Marcin
