### ISSUE TITLE
[docs] deprecated method in example

### ISSUE THREAD

**Issue by mtmccrea** [ambisonictoolkit/atk-sc3#82]
In the docs Guide to ATK Matrix Files > Writing raw matrices, an example uses a deprecated method:

```
(
~atkMatrix = ~matrix.asAtkMatrix('FOA', 'encoder'); // set, type
// be sure to use .yml extension for metadata
~atkMatrix.writeToFile("myA2B_flu_Matrix.yml", ~note, ~properties);
)
```
`asAtkMatrix` was not adopted, and this example should be updated with the proper method of instantiating an FOA matrix to write to file

**Comment by joslloand** [comment]
Closed for sandbox/hoa
