### ISSUE TITLE
Installed quark appears to be missing stuff or misconfigured

### ISSUE THREAD

**Issue by forrcaho** [ambisonictoolkit/atk-sc3#87]
I'm new to Supercollider, so please bear with me if I don't get all the terminology right.

The version of Supercollider I'm using I built from git sources on a Debian "unstable" linux machine.
I installed the ATK quark using the command in your instructions:
```
Quarks.install("https://github.com/ambisonictoolkit/atk-sc3.git");
```
This appears to have worked correctly, because I see this message in the post window on restart:
 ```
compiling class library...
	Found 866 primitives.
	Compiling directory '/usr/local/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/local/share/SuperCollider/Extensions'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/Extensions'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/FileLog'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/MathLib'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/ExtraWindows'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/SignalBox'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/Hilbert'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/XML'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/wslib'
	Compiling directory '/home/forrcaho/.local/share/SuperCollider/downloaded-quarks/atk-sc3'
	numentries = 1129631 / 22700910 = 0.05
	7801 method selectors, 2910 classes
	method table size 21360840 bytes, big table size 181607280
	Number of Symbols 18249
	Byte Code Size 711835
	compiled 621 files in 0.56 seconds
```
I also see the ATK documentation in my help browser. I go to the page "SynthDef and NRT examples for ATK" in the guides, which contains a number of examples it appears I should be able to run directly if ATK is properly installed.

The first and last code examples ("Mono Encoder using FoaPanB" and "Route Encoding Synth to a separate Decoding Synth") give the following error:
```
exception in GraphDef_Recv: UGen 'FoaPanB' not installed.
```
The second code example ("Omni Encoder using FoaEncoderMatrix, Transforms using FoaTransform") gives a long error message that starts with
```
No folder found in
	PathName(/home/forrcaho/.local/share/ATK/matrices)
or
	PathName(/usr/local/share/ATK/matrices)
```
In fact, there is no ATK directory in either of these locations.

It looks to me like either installing the quark doesn't give me all the required files, or there's some place where paths aren't being set correctly, or both.

**Comment by joslloand** [comment]
Hello @forrcaho 

First off, welcome to SuperCollider and the ATK.

Thanks for the detailed posting. The short answer is, yes, the quark doesn't install all the required files. Instructions for installation are listed on the [Ambisonic Toolkit installation page](http://www.ambisonictoolkit.net/download/supercollider/). There are three things you need to install:

1. atk-sc3 Quark: you've done this!
2. [sc3-plugins](https://github.com/supercollider/sc3-plugins): you haven't done this, that's where the error for FoaPanB is coming from
3. [Kernels, Matrices & Recordings](http://www.ambisonictoolkit.net/download/supercollider/): thats where the matrices error comes from

You should be good to go when you finish off the last to steps.

FYI: We have plans for a future version of the quark to automagically install the required kernels and matrices.
