### ISSUE TITLE
convenience install method fails on macOS 10.15.7

### ISSUE THREAD

**Issue by telephon** [ambisonictoolkit/atk-sc3#91]
This is on macOS 10.15.7, with SuperCollider being allowed to access "Files and Folders".

```
Atk.downloadKernels;
```

results in:

```
curl: (7) Couldn't connect to server
download error, exit code 7
If you would like to proceed with manual installation, please see the Ambisonic Toolkit webpage at ambisonictoolkit.net or run "http://ambisonictoolkit.net".openOS
```

Tracing it down in  `ATK.downloadFile`, the generated command is:
```
"curl -L https://github.com/ambisonictoolkit/atk-kernels/releases/latest/download/kernels.zip --output '/Users/julian/Library/Application Support/SuperCollider/tmp/2023206293kernels.zip' -# 2>&1"
```

Which in bash gives me "No such file or directory":

```
"curl -L https://github.com/ambisonictoolkit/atk-kernels/releases/latest/download/kernels.zip --output '/Users/julian/Library/Application Support/SuperCollider/tmp/2023206293kernels.zip' -# 2>&1"
-bash: curl -L https://github.com/ambisonictoolkit/atk-kernels/releases/latest/download/kernels.zip --output '/Users/julian/Library/Application Support/SuperCollider/tmp/2023206293kernels.zip' -# 2>&1: No such file or directory
```

**Comment by joslloand** [comment]
@dyfer can you have a look at this?

**Comment by telephon** [comment]
no, this directory doesn't exist.

**Comment by joslloand** [comment]
NOTE to self: we'd like to resolve this before announcing release on sc-users list.

**Comment by dyfer** [comment]
> no, this directory doesn't exist.

That's weird. On my system it gets created when recompiling the library. Which SC version are you running?

**Comment by dyfer** [comment]
I tested this on macOS 10.15.7 with SC 3.11.2, 3.11.1, 3.10.4, installing atk-sc3 from `Quarks.gui`. 
I cannot reproduce this problem unfortunately. Even if I manually delete `~/Library/Application Support/SuperCollider/tmp/`, it gets recreated when calling `Atk.downloadKernels` and the installation succeeds.

**Comment by telephon** [comment]
Uups, sorry. I somehow must have been blind. It *does* exist.

**Comment by telephon** [comment]
I've just tried again, and – for the first time – was asked by the OS to allow the connection. Now it downloads perfectly well. I don't know what I've done. If anyone else runs into this, please reopen, but maybe it was just some quirk in my system.
